### ISSUE TITLE
Trying to get this working in WordPress

### ISSUE THREAD

**Issue by srikat** [tjvantoll/jquery-ui-vertical-tabs#1]
Code in child theme's functions.php: http://pastebin.com/D18B7knC

Code in active theme/js/vertical-tabs-init.js: http://pastebin.com/KF5xUi4b

Code in a Page: http://pastebin.com/W7Y4V8vr

I am only getting horizontal tabs: http://cl.ly/image/2S2A2j3x122O

No JS errors in console.

Please advise.

**Comment by tjvantoll** [comment]
You can't include files from https://raw.githubusercontent.com as they have the wrong MIME types. Either download the files or use https://rawgit.com instead of https://raw.githubusercontent.com.
